import {
  Boxes,
  BookOpenText,
  CalendarCheck,
  ClipboardList,
  HardHat,
  CreditCard,
  Gauge,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  PawPrint,
  Package,
  Map,
  Library,
  type LucideIcon,
  Plug,
  Route,
  ScrollText,
  Sprout,
  Settings,
  ShoppingCart,
  ShieldCheck,
  Tractor,
  Users,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  map: Map,
  crops: Sprout,
  livestock: PawPrint,
  myday: CalendarCheck,
  tasks: ClipboardList,
  workers: HardHat,
  inventory: Package,
  procurement: ShoppingCart,
  ledger: BookOpenText,
  trace: Route,
  members: Users,
  roles: ShieldCheck,
  audit: ScrollText,
  settings: Settings,
  billing: CreditCard,
  support: LifeBuoy,
  farms: Tractor,
  plans: Boxes,
  users: KeyRound,
  catalog: Library,
  integrations: Plug,
  system: Gauge,
};
