/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Returns tokens, or `mfa_required: true` with a short-lived `mfa_token`
         *     to complete with `/auth/mfa/challenge`. Unknown emails, wrong passwords
         *     and locked accounts all return the same 401 `invalid_credentials`.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete sign-in with an authenticator or recovery code */
        post: operations["mfaChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Each refresh token works once. Replaying an old one revokes the whole session (`token_reuse_detected`).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session (all its tokens) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot password */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start authenticator-app enrolment */
        post: operations["mfaSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa confirm */
        post: operations["mfaConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa regenerate recovery codes */
        post: operations["mfaRegenerateRecoveryCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Turn MFA off (refused when the role requires it) */
        delete: operations["mfaDisable"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get me */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Farms and portals the user can enter, with permissions and dashboards */
        get: operations["listWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices/{device}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke device */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List farms */
        get: operations["listFarms"];
        put?: never;
        /** Create a farm (starts `pending` until approved by the platform) */
        post: operations["createFarm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        /** Get farm */
        get: operations["getFarm"];
        /** Replace farm */
        put: operations["replaceFarm"];
        post?: never;
        /** Close (archive) the farm. Owner only; data is retained. */
        delete: operations["closeFarm"];
        options?: never;
        head?: never;
        /** Update farm */
        patch: operations["updateFarm"];
        trace?: never;
    };
    "/farms/{farm}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/roles/{role}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a role's grants (guard-rails apply, docs/04 §4) */
        put: operations["updateRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List permissions */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit logs */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/dashboards/{dashboard}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/dashboards/{dashboard}/widgets/{widget}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard widget */
        get: operations["getDashboardWidget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/batches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        /** List batches */
        get: operations["listBatches"];
        put?: never;
        /** Create batch */
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/batches/{batch}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        /** Get batch */
        get: operations["getBatch"];
        put?: never;
        post?: never;
        /** Always refused — traceability history is permanent */
        delete: operations["deleteBatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/batches/{batch}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        /** List batch events */
        get: operations["listBatchEvents"];
        put?: never;
        /** Record batch event */
        post: operations["recordBatchEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/batches/{batch}/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get batch journey */
        get: operations["getBatchJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/batches/{batch}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a parent → this batch edge (cycles are refused) */
        post: operations["linkBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/batches/{batch}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change batch status */
        post: operations["changeBatchStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm}/traceability/events/{event}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct an event by appending a `correction` event */
        post: operations["correctEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform dashboard (platform admins only) */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            /** @description Stable machine-readable code (e.g. validation_failed, not_found, mfa_setup_required, token_reuse_detected, append_only) */
            code: string;
            errors?: {
                [key: string]: string[];
            };
            request_id?: string | null;
        };
        CursorPage: {
            links?: {
                first?: string | null;
                last?: string | null;
                prev?: string | null;
                next?: string | null;
            };
            meta?: {
                path?: string;
                per_page?: number;
                next_cursor?: string | null;
                prev_cursor?: string | null;
            };
        };
        TokenPair: {
            /** @constant */
            mfa_required?: false;
            /** @constant */
            token_type: "Bearer";
            access_token: string;
            /** @description seconds */
            expires_in: number;
            refresh_token: string;
            /** @description seconds */
            refresh_expires_in: number;
        };
        MfaPending: {
            /** @constant */
            mfa_required: true;
            mfa_token: string;
            methods?: ("totp" | "recovery_code")[];
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "user";
            /** @enum {string} */
            user_type?: "platform_admin" | "member" | "party";
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string | null;
            mfa_enabled?: boolean;
            /** Format: date-time */
            last_login_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Device: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "device";
            /** @enum {string} */
            client?: "web" | "mobile";
            name?: string | null;
            platform?: string | null;
            last_ip?: string | null;
            /** Format: date-time */
            last_seen_at?: string | null;
            current?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        /** @enum {string} */
        Scope: "all" | "assigned" | "own";
        Workspace: {
            /** @enum {string} */
            type: "platform" | "farm" | "supplier" | "customer";
            id: string;
            name: string;
            code?: string;
            status?: string;
            is_owner?: boolean;
            roles?: {
                key?: string;
                name?: string;
            }[];
            permissions?: {
                [key: string]: components["schemas"]["Scope"];
            };
            dashboards: ("admin" | "owner" | "manager" | "agronomist" | "livestock" | "store" | "accountant" | "worker")[];
        };
        FarmInput: {
            name?: string;
            organization_name?: string;
            district?: string | null;
            village?: string | null;
            country?: string;
            size_ha?: number | null;
            timezone?: string;
            currency?: string;
        };
        Farm: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "farm";
            /** Format: uuid */
            organization_id?: string;
            code?: string;
            name?: string;
            /** @enum {string} */
            status?: "pending" | "active" | "suspended" | "closed";
            district?: string | null;
            village?: string | null;
            country?: string;
            /** @description decimal string */
            size_ha?: string | null;
            timezone?: string;
            currency?: string;
            /** Format: date-time */
            approved_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Member: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "farm_member";
            user?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                email?: string;
            };
            /** @enum {string} */
            status?: "invited" | "active" | "suspended";
            is_owner?: boolean;
            roles?: {
                key?: string;
                name?: string;
            }[];
            /** Format: date-time */
            joined_at?: string | null;
        };
        Role: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "farm_role";
            key?: string;
            name?: string;
            description?: string | null;
            is_system?: boolean;
            is_locked?: boolean;
            grants?: {
                [key: string]: components["schemas"]["Scope"];
            };
        };
        PermissionDefinition: {
            key?: string;
            module?: string;
            description?: string;
            scopes?: components["schemas"]["Scope"][];
            owner_only?: boolean;
            money?: boolean;
        };
        AuditLog: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "audit_log";
            action?: string;
            entity_type?: string | null;
            entity_id?: string | null;
            user_id?: string | null;
            old_values?: Record<string, never> | null;
            new_values?: Record<string, never> | null;
            ip?: string | null;
            request_id?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Dashboard: {
            dashboard: string;
            farm?: {
                id?: string;
                name?: string;
                currency?: string;
                timezone?: string;
            };
            period?: {
                key?: string;
                /** Format: date */
                from?: string;
                /** Format: date */
                to?: string;
            };
            /** Format: date-time */
            generated_at: string;
            kpis: components["schemas"]["Kpi"][];
            widgets: components["schemas"]["WidgetRef"][];
            quick_actions: {
                key?: string;
                label?: string;
                target?: string;
            }[];
            alerts: {
                /** @enum {string} */
                severity?: "low" | "medium" | "high";
                type?: string;
                message?: string;
                href?: string;
            }[];
        };
        Kpi: {
            key: string;
            label: string;
            /** @description number, money {amount,currency}, quantity {value,unit}, status string, or null */
            value: unknown;
            /** @enum {string} */
            format: "number" | "money" | "percent" | "quantity" | "duration" | "status";
            delta?: null | {
                value?: number | null;
                /** @enum {string} */
                direction?: "up" | "down" | "flat";
                vs?: string;
            };
            meta?: Record<string, never>;
        };
        WidgetRef: {
            key: string;
            /** @enum {string} */
            type: "action_list" | "checklist" | "chart" | "map" | "timeline";
            inline: boolean;
            /** @description Present when inline */
            data?: {
                [key: string]: unknown;
            };
            /** @description Present when not inline */
            href?: string;
        };
        ChartWidget: {
            key?: string;
            /** @constant */
            type?: "chart";
            /** @enum {string} */
            chart?: "bar" | "line" | "bar_line";
            x?: {
                type?: string;
                values?: string[];
            };
            series?: {
                key?: string;
                label?: string;
                unit?: string;
                values?: number[];
            }[];
        };
        /** @enum {string} */
        BatchKind: "seed_lot" | "input_lot" | "nursery" | "crop_lot" | "harvest" | "animal" | "animal_product" | "processed" | "packaged" | "shipment";
        /** @enum {string} */
        BatchStatus: "open" | "closed" | "recalled";
        /** @enum {string} */
        LinkType: "derived" | "split" | "merge" | "process" | "package" | "ship";
        Quantity: {
            /** @description decimal string */
            value?: string;
            unit?: string | null;
        };
        Location: {
            lat: number;
            lng: number;
            accuracy_m?: number | null;
        };
        Batch: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "trace_batch";
            batch_code?: string;
            kind?: components["schemas"]["BatchKind"];
            name?: string | null;
            status?: components["schemas"]["BatchStatus"];
            quantity?: components["schemas"]["Quantity"] | null;
            origin_plot_id?: string | null;
            source?: null | {
                type?: string;
                id?: string;
            };
            version?: number;
            created_by?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TraceEvent: {
            /** Format: uuid */
            id?: string;
            /** @constant */
            type?: "trace_event";
            /** Format: uuid */
            batch_id?: string;
            event_type?: string;
            /** Format: date-time */
            occurred_at?: string;
            /** Format: date-time */
            recorded_at?: string;
            /** @description occurred_at and recorded_at differ by over an hour */
            recorded_late?: boolean;
            actor_user_id?: string | null;
            worker_id?: string | null;
            plot_id?: string | null;
            location?: components["schemas"]["Location"] | null;
            subject?: null | {
                type?: string;
                id?: string;
            };
            payload?: {
                [key: string]: unknown;
            };
            corrects_event_id?: string | null;
            integrity?: {
                seq?: number;
                hash?: string;
                prev_hash?: string;
            };
        };
        GraphNode: {
            /** Format: uuid */
            id?: string;
            batch_code?: string;
            kind?: components["schemas"]["BatchKind"];
            name?: string | null;
            status?: components["schemas"]["BatchStatus"];
            quantity?: components["schemas"]["Quantity"] | null;
            depth?: number;
        };
        GraphEdge: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            from?: string;
            /** Format: uuid */
            to?: string;
            link_type?: components["schemas"]["LinkType"];
            quantity?: string | null;
            unit?: string | null;
        };
        Graph: {
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
        };
    };
    responses: {
        /** @description RFC 9457 problem details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Farm: string;
        Batch: string;
        Dashboard: "owner" | "manager" | "agronomist" | "livestock" | "store" | "accountant" | "worker";
        Period: "today" | "7d" | "30d" | "90d" | "ytd" | "custom";
        Cursor: string;
        PerPage: number;
        /** @description Required from mobile clients. A repeat returns the first response with the header Idempotent-Replayed: true. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /**
                     * @default web
                     * @enum {string}
                     */
                    client?: "web" | "mobile";
                    device?: {
                        name?: string;
                        /** @enum {string} */
                        platform?: "android" | "ios" | "web";
                        push_token?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Signed in, or second factor required */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TokenPair"] | components["schemas"]["MfaPending"];
                    };
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    mfaChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    mfa_token: string;
                    code?: string;
                    recovery_code?: string;
                };
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TokenPair"];
                    };
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TokenPair"];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description A reset link is emailed if the account exists */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    token: string;
                    password: string;
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Password changed; every session is signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Problem"];
        };
    };
    mfaSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret and otpauth URI for the QR code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            secret?: string;
                            otpauth_uri?: string;
                        };
                    };
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    mfaConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description MFA enabled; recovery codes are shown once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            mfa_enabled?: boolean;
                            recovery_codes?: string[];
                        };
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    mfaRegenerateRecoveryCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description New recovery codes (old ones stop working) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            recovery_codes?: string[];
                        };
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    mfaDisable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description MFA disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["User"];
                        meta?: {
                            mfa_required?: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Workspace"][];
                        meta?: {
                            default_workspace?: string | null;
                            mfa_enabled?: boolean;
                            mfa_required?: boolean;
                        };
                    };
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed-in devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Device"][];
                    };
                };
            };
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listFarms: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Farms the user is an active member of */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        data?: components["schemas"]["Farm"][];
                    };
                };
            };
        };
    };
    createFarm: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required from mobile clients. A repeat returns the first response with the header Idempotent-Replayed: true. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmInput"];
            };
        };
        responses: {
            /** @description Farm created; the caller is its owner */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Farm"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getFarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Farm profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Farm"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    replaceFarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Farm"];
                    };
                };
            };
        };
    };
    closeFarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
        };
    };
    updateFarm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Farm"];
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    listMembers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Farm members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        data?: components["schemas"]["Member"][];
                    };
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Farm roles with grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Role"][];
                    };
                };
            };
        };
    };
    updateRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                role: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    grants: {
                        [key: string]: components["schemas"]["Scope"];
                    };
                };
            };
        };
        responses: {
            /** @description Updated role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Role"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permission registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PermissionDefinition"][];
                    };
                };
            };
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                per_page?: components["parameters"]["PerPage"];
                "filter[action]"?: string;
                "filter[entity_type]"?: string;
                "filter[entity_id]"?: string;
                "filter[user_id]"?: string;
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        data?: components["schemas"]["AuditLog"][];
                    };
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                period?: components["parameters"]["Period"];
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                dashboard: components["parameters"]["Dashboard"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary (KPIs, widgets, quick actions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Dashboard"];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    getDashboardWidget: {
        parameters: {
            query?: {
                period?: components["parameters"]["Period"];
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                dashboard: components["parameters"]["Dashboard"];
                widget: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One heavy widget (chart, map) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ChartWidget"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listBatches: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                per_page?: components["parameters"]["PerPage"];
                "filter[kind]"?: components["schemas"]["BatchKind"];
                "filter[status]"?: components["schemas"]["BatchStatus"];
                /** @description Search batch code or name */
                q?: string;
                sort?: "created_at" | "-created_at" | "batch_code" | "-batch_code";
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Batches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        data?: components["schemas"]["Batch"][];
                    };
                };
            };
        };
    };
    createBatch: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required from mobile clients. A repeat returns the first response with the header Idempotent-Replayed: true. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                farm: components["parameters"]["Farm"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "seed_lot" | "input_lot" | "processed" | "packaged";
                    name?: string;
                    quantity?: number;
                    unit?: string;
                    /** Format: date-time */
                    occurred_at?: string;
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Batch created (with its `created` event) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Batch"];
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Batch */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Batch"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            405: components["responses"]["Problem"];
        };
    };
    listBatchEvents: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event timeline in occurred_at order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        data?: components["schemas"]["TraceEvent"][];
                    };
                };
            };
        };
    };
    recordBatchEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required from mobile clients. A repeat returns the first response with the header Idempotent-Replayed: true. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    event_type: "note" | "inspection" | "certification" | "storage_check";
                    /** Format: date-time */
                    occurred_at?: string;
                    payload?: {
                        [key: string]: unknown;
                    };
                    location?: components["schemas"]["Location"];
                };
            };
        };
        responses: {
            /** @description Event appended */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TraceEvent"];
                    };
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getBatchJourney: {
        parameters: {
            query?: {
                direction?: "backward" | "forward" | "both";
                depth?: number;
            };
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upstream and/or downstream graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            batch?: components["schemas"]["Batch"];
                            backward?: components["schemas"]["Graph"] | null;
                            forward?: components["schemas"]["Graph"] | null;
                            evidence_summary?: {
                                events?: number;
                                gps_points?: number;
                            };
                        };
                    };
                };
            };
        };
    };
    linkBatch: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required from mobile clients. A repeat returns the first response with the header Idempotent-Replayed: true. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    parent_batch_id: string;
                    link_type: components["schemas"]["LinkType"];
                    quantity?: number;
                    unit?: string;
                };
            };
        };
        responses: {
            /** @description Link created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GraphEdge"];
                    };
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    changeBatchStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                batch: components["parameters"]["Batch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["BatchStatus"];
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Status changed (recorded as a `status_changed` event) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Batch"];
                    };
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    correctEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm: components["parameters"]["Farm"];
                event: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    payload: {
                        [key: string]: unknown;
                    };
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Correction event */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TraceEvent"];
                    };
                };
            };
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform KPIs; never farm operational data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Dashboard"];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
}
