<?php
/* Defaults for new farms: role templates, settings and the chart of accounts (exported from the earlier version). */

const ROLE_TEMPLATES = array (
  'owner' => 
  array (
    'name' => 'Farm Owner',
    'description' => 'Highest authority in the farm. Always holds every permission.',
    'grants' => 
    array (
      'farm.profile.view' => 'all',
      'farm.profile.manage' => 'all',
      'farm.settings.manage' => 'all',
      'farm.delete' => 'all',
      'farm.transfer' => 'all',
      'billing.manage' => 'all',
      'members.view' => 'all',
      'members.manage' => 'all',
      'members.invite_workers' => 'all',
      'roles.view' => 'all',
      'roles.manage' => 'all',
      'dashboard.owner.view' => 'all',
      'dashboard.manager.view' => 'all',
      'dashboard.agronomist.view' => 'all',
      'dashboard.livestock.view' => 'all',
      'dashboard.store.view' => 'all',
      'dashboard.accountant.view' => 'all',
      'dashboard.worker.view' => 'all',
      'structure.view' => 'all',
      'structure.manage' => 'all',
      'structure.soil.manage' => 'all',
      'crops.plans.view' => 'all',
      'crops.plans.manage' => 'all',
      'crops.plans.approve' => 'all',
      'crops.operations.view' => 'all',
      'crops.operations.record' => 'all',
      'crops.operations.approve' => 'all',
      'crops.harvest.view' => 'all',
      'crops.harvest.record' => 'all',
      'livestock.animals.view' => 'all',
      'livestock.animals.manage' => 'all',
      'livestock.records.record' => 'all',
      'livestock.records.approve' => 'all',
      'livestock.sales.request' => 'all',
      'livestock.sales.approve' => 'all',
      'workers.view' => 'all',
      'workers.manage' => 'all',
      'tasks.view' => 'all',
      'tasks.manage' => 'all',
      'tasks.execute' => 'assigned',
      'tasks.verify' => 'all',
      'attendance.view' => 'all',
      'attendance.record' => 'own',
      'attendance.approve' => 'all',
      'leave.request' => 'own',
      'leave.approve' => 'all',
      'worker.gps.view' => 'all',
      'inventory.view' => 'all',
      'inventory.manage' => 'all',
      'inventory.stock.move' => 'all',
      'inventory.stock.adjust' => 'all',
      'inventory.stock.approve' => 'all',
      'inventory.requests.create' => 'all',
      'inventory.values.view' => 'all',
      'procurement.requests.create' => 'all',
      'procurement.requests.approve' => 'all',
      'procurement.orders.manage' => 'all',
      'procurement.orders.approve' => 'all',
      'procurement.deliveries.receive' => 'all',
      'suppliers.view' => 'all',
      'suppliers.manage' => 'all',
      'finance.view' => 'all',
      'finance.manage' => 'all',
      'finance.approve' => 'all',
      'finance.expenses.request' => 'all',
      'finance.budgets.manage' => 'all',
      'finance.payroll.view_hours' => 'all',
      'finance.payroll.manage' => 'all',
      'finance.payroll.approve' => 'all',
      'finance.values.view' => 'all',
      'sales.view' => 'all',
      'sales.pricing.manage' => 'all',
      'sales.orders.create' => 'all',
      'sales.orders.approve' => 'all',
      'sales.fulfil' => 'all',
      'sales.invoice' => 'all',
      'customers.view' => 'all',
      'customers.manage' => 'all',
      'assets.view' => 'all',
      'assets.manage' => 'all',
      'assets.maintenance.record' => 'all',
      'trace.batches.view' => 'all',
      'trace.batches.create' => 'all',
      'trace.events.create' => 'all',
      'trace.publish' => 'all',
      'trace.qr.manage' => 'all',
      'maps.view' => 'all',
      'reports.view' => 'all',
      'reports.export' => 'all',
      'reports.finance.view' => 'all',
      'documents.view' => 'all',
      'documents.manage' => 'all',
      'audit.view' => 'all',
    ),
  ),
  'manager' => 
  array (
    'name' => 'Farm Manager',
    'description' => 'Runs daily operations, workers, tasks and approvals.',
    'grants' => 
    array (
      'farm.profile.view' => 'all',
      'structure.view' => 'all',
      'structure.manage' => 'all',
      'structure.soil.manage' => 'all',
      'members.view' => 'all',
      'members.invite_workers' => 'all',
      'roles.view' => 'all',
      'dashboard.manager.view' => 'all',
      'crops.plans.view' => 'all',
      'crops.plans.manage' => 'all',
      'crops.operations.view' => 'all',
      'crops.operations.record' => 'all',
      'crops.operations.approve' => 'all',
      'crops.harvest.view' => 'all',
      'crops.harvest.record' => 'all',
      'livestock.animals.view' => 'all',
      'livestock.animals.manage' => 'all',
      'livestock.records.record' => 'all',
      'livestock.records.approve' => 'all',
      'livestock.sales.request' => 'all',
      'workers.view' => 'all',
      'workers.manage' => 'all',
      'tasks.view' => 'all',
      'tasks.manage' => 'all',
      'tasks.verify' => 'all',
      'attendance.view' => 'all',
      'attendance.approve' => 'all',
      'leave.approve' => 'all',
      'worker.gps.view' => 'all',
      'inventory.view' => 'all',
      'inventory.stock.approve' => 'all',
      'inventory.requests.create' => 'all',
      'procurement.requests.create' => 'all',
      'procurement.requests.approve' => 'all',
      'suppliers.view' => 'all',
      'finance.expenses.request' => 'all',
      'finance.payroll.view_hours' => 'all',
      'sales.view' => 'all',
      'sales.orders.create' => 'all',
      'sales.fulfil' => 'all',
      'customers.view' => 'all',
      'assets.view' => 'all',
      'assets.manage' => 'all',
      'assets.maintenance.record' => 'all',
      'trace.batches.view' => 'all',
      'trace.batches.create' => 'all',
      'trace.events.create' => 'all',
      'trace.publish' => 'all',
      'maps.view' => 'all',
      'reports.view' => 'all',
      'reports.export' => 'all',
      'documents.view' => 'all',
      'documents.manage' => 'all',
      'audit.view' => 'all',
    ),
  ),
  'agronomist' => 
  array (
    'name' => 'Agronomist',
    'description' => 'Crop planning, field operations, pests and disease, harvest.',
    'grants' => 
    array (
      'farm.profile.view' => 'all',
      'structure.view' => 'all',
      'structure.soil.manage' => 'all',
      'dashboard.agronomist.view' => 'all',
      'crops.plans.view' => 'all',
      'crops.plans.manage' => 'all',
      'crops.operations.view' => 'all',
      'crops.operations.record' => 'all',
      'crops.operations.approve' => 'all',
      'crops.harvest.view' => 'all',
      'crops.harvest.record' => 'all',
      'workers.view' => 'all',
      'tasks.view' => 'all',
      'tasks.manage' => 'all',
      'tasks.verify' => 'all',
      'attendance.view' => 'all',
      'worker.gps.view' => 'all',
      'inventory.view' => 'all',
      'inventory.requests.create' => 'all',
      'procurement.requests.create' => 'all',
      'trace.batches.view' => 'all',
      'trace.batches.create' => 'all',
      'trace.events.create' => 'all',
      'trace.publish' => 'all',
      'maps.view' => 'all',
      'reports.view' => 'all',
      'documents.view' => 'all',
      'documents.manage' => 'all',
    ),
  ),
  'livestock_manager' => 
  array (
    'name' => 'Livestock Manager',
    'description' => 'Animals, breeding, feeding, health, production and movements.',
    'grants' => 
    array (
      'farm.profile.view' => 'all',
      'structure.view' => 'all',
      'dashboard.livestock.view' => 'all',
      'livestock.animals.view' => 'all',
      'livestock.animals.manage' => 'all',
      'livestock.records.record' => 'all',
      'livestock.records.approve' => 'all',
      'livestock.sales.request' => 'all',
      'workers.view' => 'all',
      'tasks.view' => 'all',
      'tasks.manage' => 'all',
      'tasks.verify' => 'all',
      'attendance.view' => 'all',
      'worker.gps.view' => 'all',
      'inventory.view' => 'all',
      'inventory.requests.create' => 'all',
      'procurement.requests.create' => 'all',
      'trace.batches.view' => 'all',
      'trace.batches.create' => 'all',
      'trace.events.create' => 'all',
      'trace.publish' => 'all',
      'maps.view' => 'all',
      'reports.view' => 'all',
      'documents.view' => 'all',
      'documents.manage' => 'all',
    ),
  ),
  'store_manager' => 
  array (
    'name' => 'Store Manager',
    'description' => 'Stock, stores, issues, transfers, deliveries. Requests purchases; does not buy or set prices.',
    'grants' => 
    array (
      'farm.profile.view' => 'all',
      'structure.view' => 'all',
      'dashboard.store.view' => 'all',
      'inventory.view' => 'all',
      'inventory.manage' => 'all',
      'inventory.stock.move' => 'all',
      'inventory.stock.adjust' => 'all',
      'inventory.requests.create' => 'all',
      'inventory.values.view' => 'all',
      'crops.harvest.view' => 'all',
      'procurement.requests.create' => 'all',
      'procurement.deliveries.receive' => 'all',
      'suppliers.view' => 'all',
      'sales.fulfil' => 'all',
      'assets.view' => 'all',
      'trace.batches.view' => 'all',
      'trace.batches.create' => 'all',
      'trace.events.create' => 'all',
      'maps.view' => 'all',
      'reports.view' => 'all',
      'documents.view' => 'all',
      'documents.manage' => 'all',
      'tasks.view' => 'assigned',
      'tasks.execute' => 'assigned',
    ),
  ),
  'accountant' => 
  array (
    'name' => 'Accountant',
    'description' => 'Income, expenses, invoices, payments, payroll and financial reports. Cannot change operational records.',
    'grants' => 
    array (
      'farm.profile.view' => 'all',
      'structure.view' => 'all',
      'dashboard.accountant.view' => 'all',
      'crops.plans.view' => 'all',
      'crops.operations.view' => 'all',
      'crops.harvest.view' => 'all',
      'livestock.animals.view' => 'all',
      'workers.view' => 'all',
      'attendance.view' => 'all',
      'inventory.view' => 'all',
      'inventory.values.view' => 'all',
      'procurement.orders.manage' => 'all',
      'suppliers.view' => 'all',
      'suppliers.manage' => 'all',
      'finance.view' => 'all',
      'finance.manage' => 'all',
      'finance.budgets.manage' => 'all',
      'finance.payroll.manage' => 'all',
      'finance.values.view' => 'all',
      'sales.view' => 'all',
      'sales.invoice' => 'all',
      'customers.view' => 'all',
      'customers.manage' => 'all',
      'assets.view' => 'all',
      'trace.batches.view' => 'all',
      'reports.view' => 'all',
      'reports.export' => 'all',
      'reports.finance.view' => 'all',
      'documents.view' => 'all',
      'documents.manage' => 'all',
      'audit.view' => 'all',
    ),
  ),
  'field_worker' => 
  array (
    'name' => 'Field Worker',
    'description' => 'Executes assigned tasks on mobile. No access to money, stock values or other workers.',
    'grants' => 
    array (
      'worker.self' => 'all',
      'dashboard.worker.view' => 'all',
      'structure.view' => 'assigned',
      'workers.view' => 'own',
      'tasks.view' => 'assigned',
      'tasks.execute' => 'assigned',
      'attendance.view' => 'own',
      'attendance.record' => 'own',
      'leave.request' => 'own',
      'crops.operations.record' => 'assigned',
      'crops.harvest.record' => 'assigned',
      'livestock.records.record' => 'assigned',
      'inventory.requests.create' => 'own',
      'assets.maintenance.record' => 'assigned',
      'maps.view' => 'assigned',
      'documents.view' => 'own',
    ),
  ),
);

const DEFAULT_FARM_SETTINGS = array (
  'require_mfa_for_all' => false,
  'approval_thresholds' => 
  array (
    'expense' => NULL,
    'purchase_order' => NULL,
    'sales_order' => NULL,
    'stock_adjustment_pct' => NULL,
  ),
  'allow_negative_stock' => false,
  'allow_intercropping' => false,
  'units' => 'metric',
  'online_payments' => 
  array (
    'enabled' => false,
    'subaccount_id' => NULL,
  ),
);

const DEFAULT_CHART = array (
  0 => 
  array (
    'code' => '1000',
    'name' => 'Cash',
    'description' => NULL,
    'type' => 'asset',
    'is_cash' => 1,
    'is_system' => 1,
  ),
  1 => 
  array (
    'code' => '1010',
    'name' => 'Mobile money and bank',
    'description' => NULL,
    'type' => 'asset',
    'is_cash' => 1,
    'is_system' => 1,
  ),
  2 => 
  array (
    'code' => '1200',
    'name' => 'Accounts receivable',
    'description' => NULL,
    'type' => 'asset',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  3 => 
  array (
    'code' => '1300',
    'name' => 'Inventory',
    'description' => NULL,
    'type' => 'asset',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  4 => 
  array (
    'code' => '2000',
    'name' => 'Accounts payable',
    'description' => NULL,
    'type' => 'liability',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  5 => 
  array (
    'code' => '2100',
    'name' => 'Goods received, not invoiced',
    'description' => NULL,
    'type' => 'liability',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  6 => 
  array (
    'code' => '2200',
    'name' => 'Wages payable',
    'description' => NULL,
    'type' => 'liability',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  7 => 
  array (
    'code' => '2210',
    'name' => 'Payroll deductions payable',
    'description' => NULL,
    'type' => 'liability',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  8 => 
  array (
    'code' => '3000',
    'name' => 'Owner\'s equity',
    'description' => NULL,
    'type' => 'equity',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  9 => 
  array (
    'code' => '3100',
    'name' => 'Opening balances',
    'description' => NULL,
    'type' => 'equity',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  10 => 
  array (
    'code' => '4000',
    'name' => 'Sales',
    'description' => NULL,
    'type' => 'income',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  11 => 
  array (
    'code' => '4100',
    'name' => 'Other income',
    'description' => NULL,
    'type' => 'income',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  12 => 
  array (
    'code' => '4200',
    'name' => 'Livestock and produce sales',
    'description' => NULL,
    'type' => 'income',
    'is_cash' => 0,
    'is_system' => 0,
  ),
  13 => 
  array (
    'code' => '5000',
    'name' => 'Inputs used (feed, seed, fertilizer, drugs …)',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  14 => 
  array (
    'code' => '5100',
    'name' => 'Stock adjustments and losses',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  15 => 
  array (
    'code' => '5200',
    'name' => 'Purchase price variance',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  16 => 
  array (
    'code' => '5300',
    'name' => 'Wages and casual labour',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 1,
  ),
  17 => 
  array (
    'code' => '5400',
    'name' => 'Fuel and transport',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 0,
  ),
  18 => 
  array (
    'code' => '5500',
    'name' => 'Veterinary and agronomy services',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 0,
  ),
  19 => 
  array (
    'code' => '5600',
    'name' => 'Repairs and maintenance',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 0,
  ),
  20 => 
  array (
    'code' => '5700',
    'name' => 'Utilities and rent',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 0,
  ),
  21 => 
  array (
    'code' => '5900',
    'name' => 'Other expenses',
    'description' => NULL,
    'type' => 'expense',
    'is_cash' => 0,
    'is_system' => 0,
  ),
);
